### ISSUE TITLE
Current State of TF-GUI

### ISSUE THREAD

**Issue by DonaldTsang** [sharmalab/tensorflow-gui#6]
It seems that https://github.com/Cloud-CV/Fabrik and https://github.com/TommyX12/tensorbuilder are getting stale, is it possible to address what TF-GUI has in terms of features?

For reference this conversation is related to https://github.com/uber/ludwig/issues/612

**Comment by vikasgola** [comment]
@DonaldTsang TF-GUI is still in development.
At present, it has these features:
- node editor which can be used to create models with basic layers like convolution, recurrent, dense, pooling, activation layers.
- node editor can also be used to create your own layer with given python code.
- node editor can also check for wrong models whose code is not possible to generate or would lead to error in code. (this check only done at the end, however this would be changed to live checking)
-  node editor auto saves the created models which can be loaded afterwards.
- generated code of node editor further can be edited in code editor any how you like which would be saved automatically. (Note that your changes to model in code editor won't be reflected in node editor i.e. node editor would show last saved model in node editor and not from the code editor. This limitation would be tried solved in future updates.)
- models can also be open directly in code editor which would load latest saved code.
- model training can be visualized in tensorboard which is integrated in GUI itself. (GUI for Testing models and saving trained models is still not implemented)

Other than the mentioned above, there are many features remaining which needs to implemented, and are currently in my mind. These features would be implemented slowly over time.

**Comment by DonaldTsang** [comment]
Is it possible to list all the missing features of the GUI in order for us to track it more easily? Ever since the downfall of Fabrik there has been a demand for such an interface waiting to be filled, and I am sure that https://github.com/biolab/orange3 outright refused to add Tensorflow to their system to be able to handle more data...

How hard is it to add elements of TensorBuilder or other libraries to TF-GUI to speed up develop, if it is even possible?

**Comment by vikasgola** [comment]
All the features which I can remember at present are...
- [x] training of models
- [ ] testing of models
- [ ] saving and loading of saved models
- [ ] option for installation of external packages which user want to install to use them in code.
- [ ] dataset viewer
- [ ] model output viewer
- [x] basic code editor
- [ ] intellisense in code editor (partially completed)
- [x] node editor with basic layers
- [x] option to create custom node in node editor (you can write your own code for that node)
- [ ] prebuilt famous models like VGG etc. in node editor
- [ ] some open source datasets as nodes in node editor which can be used directly
- [ ] option to merge nodes and create new ones
- [ ] option to specify the number of consecutive repetition of any particular node in model
- [ ] prebuilt nodes which can convert images, videos, audios and text to tfrecord to use directly them in models (conversion of images is completed)
- [x] integration of tensorboard to view training or testing progress 
- [x] projects viewer
- [ ] replace konvajs library (which handles visualization of nodes in node editor)

I would keep updating this list.

**Comment by DonaldTsang** [comment]
@vikasgola I would recommend putting this list in a separate issue, since it is very important.

**Comment by vikasgola** [comment]
@DonaldTsang Thanks for suggestion. I am going to keep it in wiki page and would also mention it in Readme.
